### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by curiousgeorgios** [the-anonymous-bs/FAVOR#1]
Have tried both the examples and uploading my own files but the gradio demo is not working with either ("Error" message just appears in chatbot component with no other info)

**Comment by the-anonymous-bs** [comment]
Hi! Thank you for your message! I have just tried the demo and the examples and they all work fine. It would be very helpful if you could provide a bit more details about how you tried the demo. 

After clicking on an example, did you see the interface become like this? 
![demo1](https://github.com/the-anonymous-bs/FAVOR/assets/23262571/b2c251d0-00fc-4729-b6aa-3832fe8f374c)
with the example prompt in the text box. After seeing this, please click submit and the system will start generating responses. 

Possible errors might occur if you click on "resubmit" when there is no previous conversation history. Also if you want to change video/audio, please click the "clear all" button because otherwise the previous input video/audio will stay there.

It would be greatly appreciated if you could give it another try and let me know if there is still any problem. Thank you very much!

**Comment by curiousgeorgios** [comment]
Tried again and it seems to work now - thanks!
